souffle: souffle::RamBreak Class Reference
souffle::RamBreak Class Reference
Breaks out of the loop if a condition holds.
#include <RamOperation.h>
Public Member Functions
RamBreak * clone () const override
Create a clone (i.e.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
RamBreak (std::unique_ptr< RamCondition > cond, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamAbstractConditional
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamCondition & getCondition () const
Get condition that must be satisfied.
RamAbstractConditional (std::unique_ptr< RamCondition > cond, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Additional Inherited Members
Protected Attributes inherited from souffle::RamAbstractConditional
std::unique_ptr< RamCondition > condition
Condition.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Detailed Description
Breaks out of the loop if a condition holds.
The following example will break out of the inner-most loop if the condition (t1.1 = 4) holds:
FOR t0 in A
  FOR t1 in B
    IF t0.1 = 4 BREAK
    ...
Definition at line 991 of file RamOperation.h.
Constructor & Destructor Documentation
RamBreak()
souffle::RamBreak::RamBreak (std::unique_ptr< RamCondition > cond, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 993 of file RamOperation.h.
             : RamAbstractConditional(std::move(cond), std::move(nested), std::move(profileText)) {}
Member Function Documentation
clone()
RamBreak* souffle::RamBreak::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamOperation.
Definition at line 1003 of file RamOperation.h.
{
         return new RamBreak(std::unique_ptr<RamCondition>(condition->clone()),
                 std::unique_ptr<RamOperation>(getOperation().clone()), getProfileText());
     }
equal()
bool souffle::RamBreak::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamAbstractConditional.
Definition at line 1009 of file RamOperation.h.
References souffle::RamAbstractConditional::equal().
{
         return RamAbstractConditional::equal(node);
     }
print()
void souffle::RamBreak::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print with indentation.
Reimplemented from souffle::RamNestedOperation.
Definition at line 997 of file RamOperation.h.
References souffle::RamNestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "IF " << getCondition() << " BREAK" << std::endl;
         RamNestedOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
RamOperation.h