souffle: souffle::AstComponent Class Reference
souffle::AstComponent Class Reference
A AST node describing a component within the input program.
#include <AstComponent.h>
Public Member Functions
void addBaseComponent (std::unique_ptr< AstComponentType > component)
add base components
void addClause (std::unique_ptr< AstClause > c)
add clause
void addComponent (std::unique_ptr< AstComponent > c)
add components
void addInstantiation (std::unique_ptr< AstComponentInit > i)
add instantiation
void addLoad (std::unique_ptr< AstLoad > load)
add load
void addOverride (const std::string &name)
add override
void addPrintSize (std::unique_ptr< AstPrintSize > printSize)
add print size
void addRelation (std::unique_ptr< AstRelation > r)
add relation
void addStore (std::unique_ptr< AstStore > store)
add store
void addType (std::unique_ptr< AstType > t)
add type
void apply (const AstNodeMapper &mapper) override
Apply the mapper to all child nodes.
AstComponent * clone () const override
Create a clone (i.e.
void copyBaseComponents (const AstComponent *other)
copy base components
const std::vector< AstComponentType * > getBaseComponents () const
get base components
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
std::vector< AstClause * > getClauses () const
get clauses
std::vector< AstComponent * > getComponents () const
get components
const AstComponentType * getComponentType () const
get component type
std::vector< AstComponentInit * > getInstantiations () const
get instantiation
std::vector< AstLoad * > getLoads () const
get loads
const std::set< std::string > & getOverridden () const
get override
std::vector< AstPrintSize * > getPrintSizes () const
get print sizes
std::vector< AstRelation * > getRelations () const
get relations
std::vector< AstStore * > getStores () const
get stores
std::vector< AstType * > getTypes () const
get types
void print (std::ostream &os) const override
Output to a given output stream.
void setComponentType (std::unique_ptr< AstComponentType > other)
set component type
Public Member Functions inherited from souffle::AstNode
AstNode ()=default
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Protected Attributes
std::vector< std::unique_ptr< AstComponentType > > baseComponents
base components of component
std::vector< std::unique_ptr< AstClause > > clauses
clauses
std::vector< std::unique_ptr< AstComponent > > components
nested components
std::unique_ptr< AstComponentType > componentType
name of component and its formal component arguments.
std::vector< std::unique_ptr< AstComponentInit > > instantiations
nested component instantiations.
std::vector< std::unique_ptr< AstLoad > > loads
I/O directives.
std::set< std::string > overrideRules
clauses of relations that are overwritten by this component
std::vector< std::unique_ptr< AstPrintSize > > printSizes
std::vector< std::unique_ptr< AstRelation > > relations
relations
std::vector< std::unique_ptr< AstStore > > stores
std::vector< std::unique_ptr< AstType > > types
types declarations
Detailed Description
A AST node describing a component within the input program.
Definition at line 157 of file AstComponent.h.
Member Function Documentation
addBaseComponent()
void souffle::AstComponent::addBaseComponent (std::unique_ptr< AstComponentType > component) inline
add base components
Definition at line 213 of file AstComponent.h.
{
         baseComponents.push_back(std::move(component));
     }
addClause()
void souffle::AstComponent::addClause (std::unique_ptr< AstClause > c) inline
add clause
Definition at line 246 of file AstComponent.h.
{
         clauses.push_back(std::move(c));
     }
addComponent()
void souffle::AstComponent::addComponent (std::unique_ptr< AstComponent > c) inline
add components
Definition at line 286 of file AstComponent.h.
{
         components.push_back(std::move(c));
     }
addInstantiation()
void souffle::AstComponent::addInstantiation (std::unique_ptr< AstComponentInit > i) inline
add instantiation
Definition at line 296 of file AstComponent.h.
{
         instantiations.push_back(std::move(i));
     }
addLoad()
void souffle::AstComponent::addLoad (std::unique_ptr< AstLoad > load) inline
add load
Definition at line 256 of file AstComponent.h.
References loads.
{
         loads.push_back(std::move(load));
     }
addOverride()
void souffle::AstComponent::addOverride (const std::string & name) inline
add override
Definition at line 306 of file AstComponent.h.
{
         overrideRules.insert(name);
     }
addPrintSize()
void souffle::AstComponent::addPrintSize (std::unique_ptr< AstPrintSize > printSize) inline
add print size
Definition at line 261 of file AstComponent.h.
References printSizes.
{
         printSizes.push_back(std::move(printSize));
     }
addRelation()
void souffle::AstComponent::addRelation (std::unique_ptr< AstRelation > r) inline
add relation
Definition at line 236 of file AstComponent.h.
References relations.
{
         relations.push_back(std::move(r));
     }
addStore()
void souffle::AstComponent::addStore (std::unique_ptr< AstStore > store) inline
add store
Definition at line 266 of file AstComponent.h.
References stores.
{
         stores.push_back(std::move(store));
     }
addType()
void souffle::AstComponent::addType (std::unique_ptr< AstType > t) inline
add type
Definition at line 218 of file AstComponent.h.
References types.
{
         types.push_back(std::move(t));
     }
apply()
void souffle::AstComponent::apply (const AstNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::AstNode.
Definition at line 353 of file AstComponent.h.
References loads, printSizes, relations, stores, and types.
{
         componentType = mapper(std::move(componentType));
         for (auto& cur : baseComponents) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : components) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : instantiations) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : types) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : relations) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : clauses) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : loads) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : printSizes) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : stores) {
             cur = mapper(std::move(cur));
         }
     }
clone()
AstComponent* souffle::AstComponent::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 315 of file AstComponent.h.
References loads, printSizes, relations, stores, and types.
{
         auto* res = new AstComponent();
         res->setComponentType(std::unique_ptr<AstComponentType>(componentType->clone()));
         for (const auto& cur : baseComponents) {
             res->baseComponents.emplace_back(cur->clone());
         }
         for (const auto& cur : components) {
             res->components.emplace_back(cur->clone());
         }
         for (const auto& cur : instantiations) {
             res->instantiations.emplace_back(cur->clone());
         }
         for (const auto& cur : types) {
             res->types.emplace_back(cur->clone());
         }
         for (const auto& cur : relations) {
             res->relations.emplace_back(cur->clone());
         }
         for (const auto& cur : clauses) {
             res->clauses.emplace_back(cur->clone());
         }
         for (const auto& cur : loads) {
             res->loads.emplace_back(cur->clone());
         }
         for (const auto& cur : printSizes) {
             res->printSizes.emplace_back(cur->clone());
         }
         for (const auto& cur : stores) {
             res->stores.emplace_back(cur->clone());
         }
         for (const auto& cur : overrideRules) {
             res->overrideRules.insert(cur);
         }
         return res;
     }
copyBaseComponents()
void souffle::AstComponent::copyBaseComponents (const AstComponent * other) inline
copy base components
Definition at line 228 of file AstComponent.h.
References getBaseComponents().
{
         baseComponents.clear();
         for (const auto& baseComponent : other->getBaseComponents()) {
             baseComponents.emplace_back(baseComponent->clone());
         }
     }
equal()
bool souffle::AstComponent::equal (const AstNode & other) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 420 of file AstComponent.h.
References souffle::equal_ptr(), souffle::equal_targets(), loads, printSizes, relations, stores, and types.
{
         assert(nullptr != dynamic_cast<const AstComponent*>(&node));
         const auto& other = static_cast<const AstComponent&>(node);
         if (equal_ptr(componentType, other.componentType)) {
             return true;
         }
         if (!equal_targets(baseComponents, other.baseComponents)) {
             return false;
         }
         if (!equal_targets(components, other.components)) {
             return false;
         }
         if (!equal_targets(instantiations, other.instantiations)) {
             return false;
         }
         if (!equal_targets(types, other.types)) {
             return false;
         }
         if (!equal_targets(relations, other.relations)) {
             return false;
         }
         if (!equal_targets(clauses, other.clauses)) {
             return false;
         }
         if (!equal_targets(loads, other.loads)) {
             return false;
         }
         if (!equal_targets(printSizes, other.printSizes)) {
             return false;
         }
         if (!equal_targets(stores, other.stores)) {
             return false;
         }
         if (overrideRules != other.overrideRules) {
             return false;
         }
         return true;
     }
getBaseComponents()
const std::vector<AstComponentType*> souffle::AstComponent::getBaseComponents () const inline
get base components
Definition at line 208 of file AstComponent.h.
References souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponent(), and copyBaseComponents().
{
         return toPtrVector(baseComponents);
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstComponent::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::AstNode.
Definition at line 384 of file AstComponent.h.
References loads, printSizes, relations, stores, and types.
{
         std::vector<const AstNode*> res;
         res.push_back(componentType.get());
         for (const auto& cur : baseComponents) {
             res.push_back(cur.get());
         }
         for (const auto& cur : components) {
             res.push_back(cur.get());
         }
         for (const auto& cur : instantiations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : types) {
             res.push_back(cur.get());
         }
         for (const auto& cur : relations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : clauses) {
             res.push_back(cur.get());
         }
         for (const auto& cur : loads) {
             res.push_back(cur.get());
         }
         for (const auto& cur : printSizes) {
             res.push_back(cur.get());
         }
         for (const auto& cur : stores) {
             res.push_back(cur.get());
         }
         return res;
     }
getClauses()
std::vector<AstClause*> souffle::AstComponent::getClauses () const inline
get clauses
Definition at line 251 of file AstComponent.h.
References souffle::toPtrVector().
{
         return toPtrVector(clauses);
     }
getComponents()
std::vector<AstComponent*> souffle::AstComponent::getComponents () const inline
get components
Definition at line 291 of file AstComponent.h.
References souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponent(), souffle::ComponentLookup::getComponent(), and souffle::ComponentLookup::run().
{
         return toPtrVector(components);
     }
getComponentType()
const AstComponentType* souffle::AstComponent::getComponentType () const inline
get component type
Definition at line 198 of file AstComponent.h.
Referenced by souffle::AstComponentChecker::checkComponent(), and souffle::AstComponentChecker::checkComponentReference().
{
         return componentType.get();
     }
getInstantiations()
std::vector<AstComponentInit*> souffle::AstComponent::getInstantiations () const inline
get instantiation
Definition at line 301 of file AstComponent.h.
References souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponent().
{
         return toPtrVector(instantiations);
     }
getLoads()
std::vector<AstLoad*> souffle::AstComponent::getLoads () const inline
get loads
Definition at line 271 of file AstComponent.h.
References loads, and souffle::toPtrVector().
{
         return toPtrVector(loads);
     }
getOverridden()
const std::set<std::string>& souffle::AstComponent::getOverridden () const inline
get override
Definition at line 311 of file AstComponent.h.
Referenced by souffle::AstComponentChecker::checkComponent().
{
         return overrideRules;
     }
getPrintSizes()
std::vector<AstPrintSize*> souffle::AstComponent::getPrintSizes () const inline
get print sizes
Definition at line 276 of file AstComponent.h.
References printSizes, and souffle::toPtrVector().
{
         return toPtrVector(printSizes);
     }
getRelations()
std::vector<AstRelation*> souffle::AstComponent::getRelations () const inline
get relations
Definition at line 241 of file AstComponent.h.
References relations, and souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponent().
{
         return toPtrVector(relations);
     }
getStores()
std::vector<AstStore*> souffle::AstComponent::getStores () const inline
get stores
Definition at line 281 of file AstComponent.h.
References stores, and souffle::toPtrVector().
{
         return toPtrVector(stores);
     }
getTypes()
std::vector<AstType*> souffle::AstComponent::getTypes () const inline
get types
Definition at line 223 of file AstComponent.h.
References souffle::toPtrVector(), and types.
{
         return toPtrVector(types);
     }
print()
void souffle::AstComponent::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 159 of file AstComponent.h.
References souffle::join(), loads, printSizes, relations, stores, and types.
{
         os << ".comp " << *componentType << " ";
         if (!baseComponents.empty()) {
             os << ": " << join(baseComponents, ",", print_deref<std::unique_ptr<AstComponentType>>()) << " ";
         }
         os << "{\n";
         if (!components.empty()) {
             os << join(components, "\n", print_deref<std::unique_ptr<AstComponent>>()) << "\n";
         }
         if (!instantiations.empty()) {
             os << join(instantiations, "\n", print_deref<std::unique_ptr<AstComponentInit>>()) << "\n";
         }
         if (!types.empty()) {
             os << join(types, "\n", print_deref<std::unique_ptr<AstType>>()) << "\n";
         }
         if (!relations.empty()) {
             os << join(relations, "\n", print_deref<std::unique_ptr<AstRelation>>()) << "\n";
         }
         if (!overrideRules.empty()) {
             os << ".override ";
             os << join(overrideRules, ",") << "\n";
         }
         if (!clauses.empty()) {
             os << join(clauses, "\n\n", print_deref<std::unique_ptr<AstClause>>()) << "\n";
         }
         if (!loads.empty()) {
             os << join(loads, "\n\n", print_deref<std::unique_ptr<AstLoad>>()) << "\n";
         }
         if (!printSizes.empty()) {
             os << join(printSizes, "\n\n", print_deref<std::unique_ptr<AstPrintSize>>()) << "\n";
         }
         if (!stores.empty()) {
             os << join(stores, "\n\n", print_deref<std::unique_ptr<AstStore>>()) << "\n";
         }
         os << "}\n";
     }
setComponentType()
void souffle::AstComponent::setComponentType (std::unique_ptr< AstComponentType > other) inline
set component type
Definition at line 203 of file AstComponent.h.
{
         componentType = std::move(other);
     }
Field Documentation
baseComponents
std::vector<std::unique_ptr<AstComponentType> > souffle::AstComponent::baseComponents protected
base components of component
Definition at line 464 of file AstComponent.h.
clauses
std::vector<std::unique_ptr<AstClause> > souffle::AstComponent::clauses protected
clauses
Definition at line 473 of file AstComponent.h.
components
std::vector<std::unique_ptr<AstComponent> > souffle::AstComponent::components protected
nested components
Definition at line 481 of file AstComponent.h.
componentType
std::unique_ptr<AstComponentType> souffle::AstComponent::componentType protected
name of component and its formal component arguments.
Definition at line 461 of file AstComponent.h.
instantiations
std::vector<std::unique_ptr<AstComponentInit> > souffle::AstComponent::instantiations protected
nested component instantiations.
Definition at line 484 of file AstComponent.h.
loads
std::vector<std::unique_ptr<AstLoad> > souffle::AstComponent::loads protected
I/O directives.
Definition at line 476 of file AstComponent.h.
overrideRules
std::set<std::string> souffle::AstComponent::overrideRules protected
clauses of relations that are overwritten by this component
Definition at line 487 of file AstComponent.h.
printSizes
std::vector<std::unique_ptr<AstPrintSize> > souffle::AstComponent::printSizes protected
Definition at line 477 of file AstComponent.h.
relations
std::vector<std::unique_ptr<AstRelation> > souffle::AstComponent::relations protected
relations
Definition at line 470 of file AstComponent.h.
stores
std::vector<std::unique_ptr<AstStore> > souffle::AstComponent::stores protected
Definition at line 478 of file AstComponent.h.
types
std::vector<std::unique_ptr<AstType> > souffle::AstComponent::types protected
types declarations
Definition at line 467 of file AstComponent.h.
The documentation for this class was generated from the following file:
AstComponent.h