souffle: souffle::ComponentInstantiationTransformer Class Reference
souffle::ComponentInstantiationTransformer Class Reference
#include <ComponentInstantiationTransformer.h>
Public Member Functions
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Definition at line 24 of file ComponentInstantiationTransformer.h.
Member Function Documentation
getName()
std::string souffle::ComponentInstantiationTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 26 of file ComponentInstantiationTransformer.h.
References transform().
{
         return "ComponentInstantiationTransformer";
     }
transform()
bool souffle::ComponentInstantiationTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 459 of file ComponentInstantiationTransformer.cpp.
References souffle::AstProgram::clauses, souffle::AstProgram::components, souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getErrorReport(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::instantiations, souffle::AstProgram::loads, souffle::AstProgram::printSizes, souffle::AstProgram::relations, souffle::AstProgram::stores, and souffle::AstProgram::types.
Referenced by getName().
{
     // TODO: Do this without being a friend class of AstProgram
     // unbound clauses with no relation defined
     std::vector<std::unique_ptr<AstClause>> unbound;
     AstProgram& program = *translationUnit.getProgram();
     auto* componentLookup = translationUnit.getAnalysis<ComponentLookup>();
     for (const auto& cur : program.instantiations) {
         std::vector<std::unique_ptr<AstClause>> orphans;
         ComponentContent content = getInstantiatedContent(
                 *cur, nullptr, *componentLookup, orphans, translationUnit.getErrorReport());
         for (auto& type : content.types) {
             program.types.insert(std::make_pair(type->getName(), std::move(type)));
         }
         for (auto& rel : content.relations) {
             program.relations.insert(std::make_pair(rel->getName(), std::move(rel)));
         }
         for (auto& io : content.loads) {
             program.loads.push_back(std::move(io));
         }
         for (auto& io : content.printSizes) {
             program.printSizes.push_back(std::move(io));
         }
         for (auto& io : content.stores) {
             program.stores.push_back(std::move(io));
         }
         for (auto& cur : orphans) {
             auto pos = program.relations.find(cur->getHead()->getName());
             if (pos != program.relations.end()) {
                 pos->second->addClause(std::move(cur));
             } else {
                 unbound.push_back(std::move(cur));
             }
         }
     }
     // add clauses
     for (auto& cur : program.clauses) {
         auto pos = program.relations.find(cur->getHead()->getName());
         if (pos != program.relations.end()) {
             pos->second->addClause(std::move(cur));
         } else {
             unbound.push_back(std::move(cur));
         }
     }
     // remember the remaining orphan clauses
     program.clauses.clear();
     program.clauses.swap(unbound);
     /*
         // unbound directives with no relation defined
         std::vector<std::unique_ptr<AstLoad>> unboundLoads;
         std::vector<std::unique_ptr<AstPrintSize>> unboundPrintSizes;
         std::vector<std::unique_ptr<AstStore>> unboundStores;
         // add IO directives
         for (auto& cur : program.loads) {
             auto pos = program.relations.find(cur->getName());
             if (pos != program.relations.end()) {
                 pos->second->addLoad(std::move(cur));
             } else {
                 unboundLoads.push_back(std::move(cur));
             }
         }
         // remember the remaining orphan directives
         program.loads.clear();
         program.loads.swap(unboundLoads);
         for (auto& cur : program.stores) {
             auto pos = program.relations.find(cur->getName());
             if (pos != program.relations.end()) {
                 pos->second->addStore(std::move(cur));
             } else {
                 unboundStores.push_back(std::move(cur));
             }
         }
         // remember the remaining orphan directives
         program.stores.clear();
         program.stores.swap(unboundStores);
     */
     // delete components and instantiations
     program.instantiations.clear();
     program.components.clear();
     return true;
 }
The documentation for this class was generated from the following files:
ComponentInstantiationTransformer.h
ComponentInstantiationTransformer.cpp