souffle: souffle::RamLoop Class Reference
souffle::RamLoop Class Reference
Execute statement until statement terminates loop via an exit statement.
#include <RamStatement.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamLoop * clone () const override
Create a clone (i.e.
const RamStatement & getBody () const
Get loop body.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
RamLoop (std::unique_ptr< RamStatement > b)
template<typename... Stmts>
RamLoop (std::unique_ptr< RamStatement > f, std::unique_ptr< RamStatement > s, std::unique_ptr< Stmts >... rest)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
std::unique_ptr< RamStatement > body
Body of loop.
Detailed Description
Execute statement until statement terminates loop via an exit statement.
For example:
LOOP
  PARALLEL
    ...
  END PARALLEL
END LOOP
Definition at line 543 of file RamStatement.h.
Constructor & Destructor Documentation
RamLoop() [1/2]
souffle::RamLoop::RamLoop (std::unique_ptr< RamStatement > b) inline
Definition at line 545 of file RamStatement.h.
                                            : body(std::move(b)) {
         assert(body != nullptr && "Loop body is a null-pointer");
     }
RamLoop() [2/2]
template<typename... Stmts> souffle::RamLoop::RamLoop (std::unique_ptr< RamStatement > f, std::unique_ptr< RamStatement > s, std::unique_ptr< Stmts >... rest) inline
Definition at line 550 of file RamStatement.h.
             : body(std::make_unique<RamSequence>(std::move(f), std::move(s), std::move(rest)...)) {}
Member Function Documentation
apply()
void souffle::RamLoop::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 572 of file RamStatement.h.
{
         body = map(std::move(body));
     }
clone()
RamLoop* souffle::RamLoop::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamStatement.
Definition at line 568 of file RamStatement.h.
{
         return new RamLoop(std::unique_ptr<RamStatement>(body->clone()));
     }
equal()
bool souffle::RamLoop::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 577 of file RamStatement.h.
References getBody().
{
         const auto& other = static_cast<const RamLoop&>(node);
         return getBody() == other.getBody();
     }
getBody()
const RamStatement& souffle::RamLoop::getBody () const inline
Get loop body.
Definition at line 554 of file RamStatement.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::NodeGenerator::visitLoop().
{
         return *body;
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamLoop::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 564 of file RamStatement.h.
{
         return {body.get()};
     }
print()
void souffle::RamLoop::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print with indentation.
Implements souffle::RamStatement.
Definition at line 558 of file RamStatement.h.
References souffle::times().
{
         os << times(" ", tabpos) << "LOOP" << std::endl;
         body->print(os, tabpos + 1);
         os << times(" ", tabpos) << "END LOOP" << std::endl;
     }
Field Documentation
body
std::unique_ptr<RamStatement> souffle::RamLoop::body protected
Body of loop.
Definition at line 584 of file RamStatement.h.
The documentation for this class was generated from the following file:
RamStatement.h