souffle: souffle::RamLogRelationTimer Class Reference
souffle::RamLogRelationTimer Class Reference
Execution time logger for a statement.
#include <RamStatement.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamLogRelationTimer * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
RamLogRelationTimer (std::unique_ptr< RamStatement > stmt, std::string msg, std::unique_ptr< RamRelationReference > relRef)
Public Member Functions inherited from souffle::RamRelationStatement
const RamRelation & getRelation () const
Get RAM relation.
RamRelationStatement (std::unique_ptr< RamRelationReference > relRef)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Public Member Functions inherited from souffle::RamAbstractLog
void apply (const RamNodeMapper &map)
std::vector< const RamNode * > getChildNodes () const
const std::string & getMessage () const
Get logging message.
const RamStatement & getStatement () const
Get logging statement.
RamAbstractLog (std::unique_ptr< RamStatement > stmt, std::string msg)
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamAbstractLog
bool equal (const RamNode &node) const
Additional Inherited Members
Protected Attributes inherited from souffle::RamRelationStatement
std::unique_ptr< RamRelationReference > relationRef
Relation reference.
Protected Attributes inherited from souffle::RamAbstractLog
std::string message
logging message
std::unique_ptr< RamStatement > statement
logging statement
Detailed Description
Execution time logger for a statement.
Logs the execution time of a statement. Before and after the execution of the logging statement the wall-clock time is taken to compute the time duration for the statement. Duration and logging message is printed after the execution of the statement.
For example:
START_TIMER ON A "file.dl [8:1-8:8]\;"
  ...
END_TIMER
Definition at line 699 of file RamStatement.h.
Constructor & Destructor Documentation
RamLogRelationTimer()
souffle::RamLogRelationTimer::RamLogRelationTimer (std::unique_ptr< RamStatement > stmt, std::string msg, std::unique_ptr< RamRelationReference > relRef) inline
Definition at line 701 of file RamStatement.h.
             : RamRelationStatement(std::move(relRef)), RamAbstractLog(std::move(stmt), std::move(msg)) {}
Member Function Documentation
apply()
void souffle::RamLogRelationTimer::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamRelationStatement.
Definition at line 723 of file RamStatement.h.
References souffle::RamRelationStatement::apply(), and souffle::RamAbstractLog::apply().
{
         RamRelationStatement::apply(map);
         RamAbstractLog::apply(map);
     }
clone()
RamLogRelationTimer* souffle::RamLogRelationTimer::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamStatement.
Definition at line 718 of file RamStatement.h.
{
         return new RamLogRelationTimer(std::unique_ptr<RamStatement>(statement->clone()), message,
                 std::unique_ptr<RamRelationReference>(relationRef->clone()));
     }
equal()
bool souffle::RamLogRelationTimer::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamRelationStatement.
Definition at line 729 of file RamStatement.h.
References souffle::RamRelationStatement::equal(), and souffle::RamAbstractLog::equal().
{
         const auto& other = static_cast<const RamLogRelationTimer&>(node);
         return RamRelationStatement::equal(other) && RamAbstractLog::equal(other);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamLogRelationTimer::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamRelationStatement.
Definition at line 712 of file RamStatement.h.
References souffle::RamRelationStatement::getChildNodes(), and souffle::RamAbstractLog::getChildNodes().
{
         std::vector<const RamNode*> res = RamRelationStatement::getChildNodes();
         res.push_back(RamAbstractLog::getChildNodes().at(0));
         return res;
     }
print()
void souffle::RamLogRelationTimer::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print with indentation.
Implements souffle::RamStatement.
Definition at line 705 of file RamStatement.h.
References souffle::stringify(), and souffle::times().
{
         os << times(" ", tabpos) << "START_TIMER ON " << getRelation().getName() << " \""
            << stringify(message) << "\"" << std::endl;
         statement->print(os, tabpos + 1);
         os << times(" ", tabpos) << "END_TIMER" << std::endl;
     }
The documentation for this class was generated from the following file:
RamStatement.h