souffle: souffle::ReadFileCSV Class Reference
souffle::ReadFileCSV Class Reference
#include <ReadStreamCSV.h>
Public Member Functions
ReadFileCSV (const IODirectives &ioDirectives, SymbolTable &symbolTable, RecordTable &recordTable)
std::unique_ptr< RamDomain[]> readNextTuple () override
Read and return the next tuple.
~ReadFileCSV () override=default
Public Member Functions inherited from souffle::ReadStreamCSV
ReadStreamCSV (std::istream &file, const IODirectives &ioDirectives, SymbolTable &symbolTable, RecordTable &recordTable)
~ReadStreamCSV () override=default
Public Member Functions inherited from souffle::ReadStream
template<typename T >
void readAll (T &relation)
virtual ~ReadStream ()=default
Protected Member Functions
std::string getFileName (const IODirectives &ioDirectives) const
Protected Member Functions inherited from souffle::ReadStreamCSV
std::string getDelimiter (const IODirectives &ioDirectives) const
std::map< int, int > getInputColumnMap (const IODirectives &ioDirectives, const unsigned arity_) const
std::string nextElement (const std::string &line, size_t &start, size_t &end)
Protected Member Functions inherited from souffle::ReadStream
void consumeChar (const std::string &str, char c, size_t &pos)
Read past given character, consuming any preceding whitespace.
void consumeWhiteSpace (const std::string &str, size_t &pos)
Advance position in the string until first non-whitespace character.
RamDomain readRecord (const std::string &source, const std::string &recordTypeName, size_t pos=0, size_t *_consumed=nullptr)
Read a record from a string.
ReadStream (const IODirectives &ioDirectives, SymbolTable &symbolTable, RecordTable &recordTable)
RamDomain readStringInRecord (const std::string &source, const size_t pos, size_t *_consumed)
Protected Attributes
std::string baseName
std::ifstream fileHandle
Protected Attributes inherited from souffle::ReadStreamCSV
const std::string delimiter
std::istream & file
std::map< int, int > inputMap
size_t lineNumber
Protected Attributes inherited from souffle::ReadStream
size_t arity
size_t auxiliaryArity
RecordTable & recordTable
SymbolTable & symbolTable
std::vector< std::string > typeAttributes
Json types
Detailed Description
Definition at line 209 of file ReadStreamCSV.h.
Constructor & Destructor Documentation
ReadFileCSV()
souffle::ReadFileCSV::ReadFileCSV (const IODirectives & ioDirectives, SymbolTable & symbolTable, RecordTable & recordTable) inline
Definition at line 211 of file ReadStreamCSV.h.
References souffle::baseName(), souffle::ReadStreamCSV::file, souffle::IODirectives::get(), and souffle::IODirectives::has().
             : ReadStreamCSV(fileHandle, ioDirectives, symbolTable, recordTable),
               baseName(souffle::baseName(getFileName(ioDirectives))),
               fileHandle(getFileName(ioDirectives), std::ios::in | std::ios::binary) {
         if (!ioDirectives.has("intermediate")) {
             if (!fileHandle.is_open()) {
                 throw std::invalid_argument("Cannot open fact file " + baseName + "\n");
             }
             // Strip headers if we're using them
             if (ioDirectives.has("headers") && ioDirectives.get("headers") == "true") {
                 std::string line;
                 getline(file, line);
             }
         }
     }
~ReadFileCSV()
souffle::ReadFileCSV::~ReadFileCSV () override default
Member Function Documentation
getFileName()
std::string souffle::ReadFileCSV::getFileName (const IODirectives & ioDirectives) const inline protected
Definition at line 247 of file ReadStreamCSV.h.
References souffle::IODirectives::get(), souffle::IODirectives::getRelationName(), and souffle::IODirectives::has().
{
         if (ioDirectives.has("filename")) {
             return ioDirectives.get("filename");
         }
         return ioDirectives.getRelationName() + ".facts";
     }
readNextTuple()
std::unique_ptr<RamDomain[]> souffle::ReadFileCSV::readNextTuple () inline override virtual
Read and return the next tuple.
Returns nullptr if no tuple was readable.
Returns
Reimplemented from souffle::ReadStreamCSV.
Definition at line 233 of file ReadStreamCSV.h.
References souffle::baseName(), e, and souffle::ReadStreamCSV::readNextTuple().
{
         try {
             return ReadStreamCSV::readNextTuple();
         } catch (std::exception& e) {
             std::stringstream errorMessage;
             errorMessage << e.what();
             errorMessage << "cannot parse fact file " << baseName << "!\n";
             throw std::invalid_argument(errorMessage.str());
         }
     }
Field Documentation
baseName
std::string souffle::ReadFileCSV::baseName protected
Definition at line 253 of file ReadStreamCSV.h.
fileHandle
std::ifstream souffle::ReadFileCSV::fileHandle protected
Definition at line 257 of file ReadStreamCSV.h.
The documentation for this class was generated from the following file:
ReadStreamCSV.h