souffle: souffle::RamLoad Class Reference
souffle::RamLoad Class Reference
Load data into a relation.
#include <RamStatement.h>
Public Member Functions
RamLoad * clone () const override
Create a clone (i.e.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
RamLoad (std::unique_ptr< RamRelationReference > relRef, std::vector< IODirectives > ioDirectives)
Public Member Functions inherited from souffle::RamAbstractLoadStore
const std::vector< IODirectives > & getIODirectives () const
Get load directives.
RamAbstractLoadStore (std::unique_ptr< RamRelationReference > relRef, std::vector< IODirectives > ioDirectives)
Public Member Functions inherited from souffle::RamRelationStatement
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get RAM relation.
RamRelationStatement (std::unique_ptr< RamRelationReference > relRef)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Additional Inherited Members
Protected Attributes inherited from souffle::RamAbstractLoadStore
const std::vector< IODirectives > ioDirectives
Load directives of a relation.
Protected Attributes inherited from souffle::RamRelationStatement
std::unique_ptr< RamRelationReference > relationRef
Relation reference.
Detailed Description
Load data into a relation.
Reads the contents of a relation and stores in a target relation reference
For example, loading with respect to some IO directives into relation A:
LOAD DATA FOR A FROM {...}
Definition at line 126 of file RamStatement.h.
Constructor & Destructor Documentation
RamLoad()
souffle::RamLoad::RamLoad (std::unique_ptr< RamRelationReference > relRef, std::vector< IODirectives > ioDirectives) inline
Definition at line 128 of file RamStatement.h.
             : RamAbstractLoadStore(std::move(relRef), std::move(ioDirectives)) {}
Member Function Documentation
clone()
RamLoad* souffle::RamLoad::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamStatement.
Definition at line 141 of file RamStatement.h.
{
         return new RamLoad(std::unique_ptr<RamRelationReference>(relationRef->clone()), ioDirectives);
     }
equal()
bool souffle::RamLoad::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamAbstractLoadStore.
Definition at line 146 of file RamStatement.h.
References souffle::RamAbstractLoadStore::equal().
{
         return RamAbstractLoadStore::equal(node);
     }
print()
void souffle::RamLoad::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print with indentation.
Implements souffle::RamStatement.
Definition at line 131 of file RamStatement.h.
References souffle::RamRelation::getName(), souffle::join(), and souffle::times().
{
         const RamRelation& rel = getRelation();
         os << times(" ", tabpos);
         os << "LOAD DATA FOR " << rel.getName() << " FROM {";
         os << join(ioDirectives, "], [",
                 [](std::ostream& out, const IODirectives& directives) { out << directives; });
         os << ioDirectives << "}";
         os << std::endl;
     };
The documentation for this class was generated from the following file:
RamStatement.h