souffle: souffle::Trie< 0u > Class Template Reference
souffle::Trie< 0u > Class Template Reference
A template specialization for the 0-ary try.
#include <Brie.h>
Data Structures
class iterator_core
The iterator core for this type of trie level.
struct op_context
Public Types
using element_type = entry_type
using iterator = typename base::template iterator< iterator_core >
using operation_hints = op_context
Public Types inherited from souffle::detail::TrieBase< 0u, Trie< 0u > >
using entry_type = typename ram::Tuple< RamDomain, Dim >
The type of the stored entries / tuples.
Public Member Functions
iterator begin () const
Obtains an iterator referencing the first element in this trie or end() if this trie is empty.
void clear ()
Clears the content of this trie.
bool contains (const entry_type &) const
Determines whether the given 0-ary tuple is present within this trie.
bool contains (const entry_type &tuple, op_context &) const
Determines whether the given 0-ary tuple is present within this trie.
bool empty () const
Determines whether this trie is empty or not.
iterator end () const
Obtains an iterator positions after the last element stored in this trie.
template<unsigned levels>
range< iterator > getBoundaries (const entry_type &) const
Obtains boundaries for the given entry.
template<unsigned levels>
range< iterator > getBoundaries (const entry_type &entry, op_context &) const
Obtains boundaries for the given entry.
std::size_t getMemoryUsage () const
Computes the total memory usage of this data structure.
bool insert (const entry_type &)
Inserts a new element into this trie.
bool insert (const entry_type &tuple, op_context &)
Inserts a new element into this trie.
void insertAll (const Trie &other)
Adds all elements of the given trie to this trie.
std::vector< range< iterator > > partition (unsigned chunks=500) const
Partitions this trie into a list of disjoint sub-sets.
std::size_t size () const
Determines the number of elements stores in this trie.
Trie ()=default
Public Member Functions inherited from souffle::detail::TrieBase< 0u, Trie< 0u > >
bool contains (Values... values) const
A generic function enabling the convenient conduction of a membership check.
const hint_statistics & getHintStatistics () const
bool insert (Values... values)
A generic function enabling the insertion of tuple values in a user-friendly way.
Private Types
using base = typename detail::TrieBase< 0u, Trie< 0u > >
using entry_type = typename ram::Tuple< RamDomain, 0 >
Private Member Functions
template<unsigned I, typename Tuple >
bool contains_internal (const Tuple &, op_context &) const
The internal implementation of the contains operation on this level as it is utilized by the TrieBase class.
template<unsigned I, typename Tuple >
iterator_core< I > getBeginCoreIterator (Tuple &) const
Initialized the core iterator of this level.
template<unsigned I, typename Tuple >
bool insert_internal (const Tuple &tuple, op_context &)
The internal implementation of the insert operation on this level as it is utilized by the TrieBase class.
Private Attributes
bool present = false
Static Private Attributes
static const ram::Tuple< RamDomain, 0 > instance
Friends
template<unsigned Dim, typename Derived >
class detail::TrieBase
template<unsigned Dim>
class Trie
Additional Inherited Members
Protected Attributes inherited from souffle::detail::TrieBase< 0u, Trie< 0u > >
hint_statistics hint_stats
Detailed Description
template<>
class souffle::Trie< 0u >
A template specialization for the 0-ary try.
Definition at line 2676 of file Brie.h.
Member Typedef Documentation
base
using souffle::Trie< 0u >::base = typename detail::TrieBase<0u, Trie<0u> > private
Definition at line 2683 of file Brie.h.
element_type
using souffle::Trie< 0u >::element_type = entry_type
Definition at line 2694 of file Brie.h.
entry_type
using souffle::Trie< 0u >::entry_type = typename ram::Tuple<RamDomain, 0> private
Definition at line 2685 of file Brie.h.
iterator
using souffle::Trie< 0u >::iterator = typename base::template iterator<iterator_core>
Definition at line 2823 of file Brie.h.
operation_hints
using souffle::Trie< 0u >::operation_hints = op_context
Definition at line 2696 of file Brie.h.
Constructor & Destructor Documentation
Trie()
souffle::Trie< 0u >::Trie () default
Member Function Documentation
begin()
iterator souffle::Trie< 0u >::begin () const inline
Obtains an iterator referencing the first element in this trie or end() if this trie is empty.
Definition at line 2829 of file Brie.h.
{
         return iterator(!present);
     }
clear()
void souffle::Trie< 0u >::clear () inline
Clears the content of this trie.
Definition at line 2707 of file Brie.h.
                  {
         present = false;
     }
contains() [1/2]
bool souffle::Trie< 0u >::contains (const entry_type &) const inline
Determines whether the given 0-ary tuple is present within this trie.
Definition at line 2764 of file Brie.h.
{
         return present;
     }
contains() [2/2]
bool souffle::Trie< 0u >::contains (const entry_type & tuple, op_context &) const inline
Determines whether the given 0-ary tuple is present within this trie.
An operation context may be provided, but ignored.
Definition at line 2772 of file Brie.h.
References souffle::contains().
{
         return contains(tuple);
     }
contains_internal()
template<unsigned I, typename Tuple > bool souffle::Trie< 0u >::contains_internal (const Tuple & , op_context &) const inline private
The internal implementation of the contains operation on this level as it is utilized by the TrieBase class.
Definition at line 2894 of file Brie.h.
{
         return present;
     }
empty()
bool souffle::Trie< 0u >::empty () const inline
Determines whether this trie is empty or not.
Definition at line 2714 of file Brie.h.
{
         return !present;
     }
end()
iterator souffle::Trie< 0u >::end () const inline
Obtains an iterator positions after the last element stored in this trie.
Definition at line 2837 of file Brie.h.
{
         return iterator();
     }
getBeginCoreIterator()
template<unsigned I, typename Tuple > iterator_core<I> souffle::Trie< 0u >::getBeginCoreIterator (Tuple &) const inline private
Initialized the core iterator of this level.
Definition at line 2876 of file Brie.h.
{
         return iterator_core<I>(!present);
     }
getBoundaries() [1/2]
template<unsigned levels> range<iterator> souffle::Trie< 0u >::getBoundaries (const entry_type &) const inline
Obtains boundaries for the given entry.
Since tuples stored in this trie have no components, the result will always be the full range [begin(),...,end()]. Levels != 0 are not allowed.
Definition at line 2856 of file Brie.h.
References souffle::make_range().
{
         static_assert(levels == 0, "No dimensions to query!");
         return make_range(begin(), end());
     }
getBoundaries() [2/2]
template<unsigned levels> range<iterator> souffle::Trie< 0u >::getBoundaries (const entry_type & entry, op_context &) const inline
Obtains boundaries for the given entry.
Since tuples stored in this trie have no components, the result will always be the full range [begin(),...,end()]. Levels != 0 are not allowed.
Definition at line 2867 of file Brie.h.
{
         return getBoundaries<levels>(entry);
     }
getMemoryUsage()
std::size_t souffle::Trie< 0u >::getMemoryUsage () const inline
Computes the total memory usage of this data structure.
Definition at line 2728 of file Brie.h.
{
         // compute the total memory usage
         return sizeof(*this);
     }
insert() [1/2]
bool souffle::Trie< 0u >::insert (const entry_type &) inline
Inserts a new element into this trie.
Returns
true if the trie has been empty before, false otherwise
Definition at line 2738 of file Brie.h.
{
         bool res = !present;
         present = true;
         return res;
     }
insert() [2/2]
bool souffle::Trie< 0u >::insert (const entry_type & tuple, op_context &) inline
Inserts a new element into this trie.
An operation context may be provided, but will be ignored.
Returns
true if the trie has been empty before, false otherwise
Definition at line 2750 of file Brie.h.
{
         return insert(tuple);
     }
insert_internal()
template<unsigned I, typename Tuple > bool souffle::Trie< 0u >::insert_internal (const Tuple & tuple, op_context &) inline private
The internal implementation of the insert operation on this level as it is utilized by the TrieBase class.
Definition at line 2885 of file Brie.h.
{
         return insert(tuple);
     }
insertAll()
void souffle::Trie< 0u >::insertAll (const Trie< 0u > & other) inline
Adds all elements of the given trie to this trie.
Definition at line 2757 of file Brie.h.
{
         present = present || other.present;
     }
partition()
std::vector<range<iterator> > souffle::Trie< 0u >::partition (unsigned chunks = 500) const inline
Partitions this trie into a list of disjoint sub-sets.
Definition at line 2844 of file Brie.h.
References souffle::make_range(), and souffle::toVector().
{
         // shortcut for empty trie
         if (empty()) return std::vector<range<iterator>>();
         return toVector(make_range(begin(), end()));
     }
size()
std::size_t souffle::Trie< 0u >::size () const inline
Determines the number of elements stores in this trie.
Definition at line 2721 of file Brie.h.
{
         return (present) ? 1 : 0;
     }
Friends And Related Function Documentation
detail::TrieBase
template<unsigned Dim, typename Derived > friend class detail::TrieBase friend
Definition at line 2681 of file Brie.h.
Trie
template<unsigned Dim> friend class Trie friend
Definition at line 2678 of file Brie.h.
Field Documentation
instance
const ram::Tuple<RamDomain, 0> souffle::Trie< 0u >::instance static private
Definition at line 2688 of file Brie.h.
present
bool souffle::Trie< 0u >::present = false private
Definition at line 2691 of file Brie.h.
The documentation for this class was generated from the following file:
Brie.h