souffle: souffle::WriteFileCSV Class Reference
souffle::WriteFileCSV Class Reference
#include <WriteStreamCSV.h>
Public Member Functions
WriteFileCSV (const IODirectives &ioDirectives, const SymbolTable &symbolTable, const RecordTable &recordTable)
~WriteFileCSV () override=default
Public Member Functions inherited from souffle::WriteStream
template<typename T >
void writeAll (const T &relation)
template<>
void writeNext (const RamDomain *tuple)
template<typename T >
void writeSize (const T &relation)
WriteStream (const IODirectives &ioDirectives, const SymbolTable &symbolTable, const RecordTable &recordTable)
virtual ~WriteStream ()=default
Protected Member Functions
void writeNextTuple (const RamDomain *tuple) override
void writeNullary () override
Protected Member Functions inherited from souffle::WriteStreamCSV
std::string getDelimiter (const IODirectives &ioDirectives) const
void writeNextTupleCSV (std::ostream &destination, const RamDomain *tuple)
void writeNextTupleElement (std::ostream &destination, const std::string &type, RamDomain value)
WriteStreamCSV (const IODirectives &ioDirectives, const SymbolTable &symbolTable, const RecordTable &recordTable)
Protected Member Functions inherited from souffle::WriteStream
void outputRecord (std::ostream &destination, const RamDomain value, const std::string &name)
template<typename Tuple >
void writeNext (const Tuple tuple)
virtual void writeSize (std::size_t)
Protected Attributes
std::ofstream file
Protected Attributes inherited from souffle::WriteStreamCSV
const std::string delimiter
Protected Attributes inherited from souffle::WriteStream
size_t arity
const RecordTable & recordTable
const bool summary
const SymbolTable & symbolTable
std::vector< std::string > typeAttributes
Json types
Detailed Description
Definition at line 83 of file WriteStreamCSV.h.
Constructor & Destructor Documentation
WriteFileCSV()
souffle::WriteFileCSV::WriteFileCSV (const IODirectives & ioDirectives, const SymbolTable & symbolTable, const RecordTable & recordTable) inline
Definition at line 85 of file WriteStreamCSV.h.
References souffle::IODirectives::get(), and souffle::IODirectives::has().
             : WriteStreamCSV(ioDirectives, symbolTable, recordTable),
               file(ioDirectives.getFileName(), std::ios::out | std::ios::binary) {
         if (ioDirectives.has("headers") && ioDirectives.get("headers") == "true") {
             file << ioDirectives.get("attributeNames") << std::endl;
         }
     }
~WriteFileCSV()
souffle::WriteFileCSV::~WriteFileCSV () override default
Member Function Documentation
writeNextTuple()
void souffle::WriteFileCSV::writeNextTuple (const RamDomain * tuple) inline override protected virtual
Implements souffle::WriteStream.
Definition at line 103 of file WriteStreamCSV.h.
References souffle::IODirectives::get(), souffle::IODirectives::getFileName(), souffle::IODirectives::has(), souffle::WriteStream::recordTable, souffle::WriteStream::symbolTable, souffle::WriteStream::writeNextTuple(), souffle::WriteStreamCSV::writeNextTupleCSV(), souffle::WriteStream::writeNullary(), and souffle::WriteStreamCSV::WriteStreamCSV().
{
         writeNextTupleCSV(file, tuple);
     }
writeNullary()
void souffle::WriteFileCSV::writeNullary () inline override protected virtual
Implements souffle::WriteStream.
Definition at line 99 of file WriteStreamCSV.h.
{
         file << "()\n";
     }
Field Documentation
file
std::ofstream souffle::WriteFileCSV::file protected
Definition at line 97 of file WriteStreamCSV.h.
The documentation for this class was generated from the following file:
WriteStreamCSV.h