souffle: souffle::AstTypeIdentifier Class Reference
souffle::AstTypeIdentifier Class Reference
The type of identifier utilized for referencing types.
#include <AstType.h>
Public Member Functions
void append (const std::string &name)
AstTypeIdentifier ()
AstTypeIdentifier (const std::string &name)
AstTypeIdentifier (const char *name)
AstTypeIdentifier (const std::vector< std::string > names)
AstTypeIdentifier (const AstTypeIdentifier &)=default
AstTypeIdentifier (AstTypeIdentifier &&)=default
bool empty () const
const std::vector< std::string > & getNames () const
bool operator!= (const AstTypeIdentifier &other) const
bool operator< (const AstTypeIdentifier &other) const
AstTypeIdentifier & operator= (const AstTypeIdentifier &)=default
AstTypeIdentifier & operator= (AstTypeIdentifier &&)=default
bool operator== (const AstTypeIdentifier &other) const
void prepend (const std::string &name)
void print (std::ostream &out) const
Private Attributes
std::vector< std::string > names
The list of names forming this identifier.
Friends
std::ostream & operator<< (std::ostream &out, const AstTypeIdentifier &id)
Detailed Description
The type of identifier utilized for referencing types.
Type name identifiers are hierarchically qualified names, e.g.
     problem.graph.edge
TODO (b-scholz): merge with AstNameIdentifier?? put it into own header file
Definition at line 40 of file AstType.h.
Constructor & Destructor Documentation
AstTypeIdentifier() [1/6]
souffle::AstTypeIdentifier::AstTypeIdentifier () inline
Definition at line 44 of file AstType.h.
Referenced by AstTypeIdentifier().
 : names() {}
AstTypeIdentifier() [2/6]
souffle::AstTypeIdentifier::AstTypeIdentifier (const std::string & name) inline
Definition at line 46 of file AstType.h.
 : names({name}) {}
AstTypeIdentifier() [3/6]
souffle::AstTypeIdentifier::AstTypeIdentifier (const char * name) inline
Definition at line 48 of file AstType.h.
 : AstTypeIdentifier(std::string(name)) {}
AstTypeIdentifier() [4/6]
souffle::AstTypeIdentifier::AstTypeIdentifier (const std::vector< std::string > names) inline
Definition at line 50 of file AstType.h.
References AstTypeIdentifier(), and operator=().
 : names(names) {}
AstTypeIdentifier() [5/6]
souffle::AstTypeIdentifier::AstTypeIdentifier (const AstTypeIdentifier &) default
AstTypeIdentifier() [6/6]
souffle::AstTypeIdentifier::AstTypeIdentifier (AstTypeIdentifier &&) default
Member Function Documentation
append()
void souffle::AstTypeIdentifier::append (const std::string & name) inline
Definition at line 62 of file AstType.h.
References names.
{
         names.push_back(name);
     }
empty()
bool souffle::AstTypeIdentifier::empty () const inline
Definition at line 72 of file AstType.h.
References names.
Referenced by souffle::AstComponentChecker::checkComponentNameReference(), and souffle::ComponentLookup::getComponent().
{
         return names.empty();
     }
getNames()
const std::vector<std::string>& souffle::AstTypeIdentifier::getNames () const inline
Definition at line 76 of file AstType.h.
References names.
{
         return names;
     }
operator!=()
bool souffle::AstTypeIdentifier::operator!= (const AstTypeIdentifier & other) const inline
Definition at line 86 of file AstType.h.
{
         return !(*this == other);
     }
operator<()
bool souffle::AstTypeIdentifier::operator< (const AstTypeIdentifier & other) const inline
Definition at line 90 of file AstType.h.
References names.
{
         return std::lexicographical_compare(
                 names.begin(), names.end(), other.names.begin(), other.names.end());
     }
operator=() [1/2]
AstTypeIdentifier& souffle::AstTypeIdentifier::operator= (const AstTypeIdentifier &) default
Referenced by AstTypeIdentifier().
operator=() [2/2]
AstTypeIdentifier& souffle::AstTypeIdentifier::operator= (AstTypeIdentifier &&) default
operator==()
bool souffle::AstTypeIdentifier::operator== (const AstTypeIdentifier & other) const inline
Definition at line 82 of file AstType.h.
References names.
{
         return names == other.names;
     }
prepend()
void souffle::AstTypeIdentifier::prepend (const std::string & name) inline
Definition at line 66 of file AstType.h.
References names.
Referenced by souffle::operator+().
{
         names.insert(names.begin(), name);
     }
print()
void souffle::AstTypeIdentifier::print (std::ostream & out) const inline
Definition at line 95 of file AstType.h.
References souffle::join(), and names.
{
         out << join(names, ".");
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const AstTypeIdentifier & id) friend
Definition at line 99 of file AstType.h.
{
         id.print(out);
         return out;
     }
Field Documentation
names
std::vector<std::string> souffle::AstTypeIdentifier::names private
The list of names forming this identifier.
Definition at line 106 of file AstType.h.
Referenced by append(), empty(), getNames(), operator<(), operator==(), prepend(), and print().
The documentation for this class was generated from the following file:
AstType.h