souffle: souffle::ParserDriver Class Reference
souffle::ParserDriver Class Reference
#include <ParserDriver.h>
Public Member Functions
void addClause (std::unique_ptr< AstClause > c)
void addComponent (std::unique_ptr< AstComponent > c)
void addFunctorDeclaration (std::unique_ptr< AstFunctorDeclaration > f)
void addInstantiation (std::unique_ptr< AstComponentInit > ci)
void addLoad (std::unique_ptr< AstLoad > d)
void addPragma (std::unique_ptr< AstPragma > p)
void addRelation (std::unique_ptr< AstRelation > r)
void addStore (std::unique_ptr< AstStore > d)
void addType (std::unique_ptr< AstType > type)
void error (const SrcLocation &loc, const std::string &msg)
void error (const std::string &msg)
souffle::SymbolTable & getSymbolTable ()
std::unique_ptr< AstTranslationUnit > parse (const std::string &filename, FILE *in, SymbolTable &symbolTable, ErrorReport &errorReport, DebugReport &debugReport)
std::unique_ptr< AstTranslationUnit > parse (const std::string &code, SymbolTable &symbolTable, ErrorReport &errorReport, DebugReport &debugReport)
ParserDriver ()
void warning (const SrcLocation &loc, const std::string &msg)
virtual ~ParserDriver ()
Static Public Member Functions
static std::unique_ptr< AstTranslationUnit > parseTranslationUnit (const std::string &filename, FILE *in, SymbolTable &symbolTable, ErrorReport &errorReport, DebugReport &debugReport)
static std::unique_ptr< AstTranslationUnit > parseTranslationUnit (const std::string &code, SymbolTable &symbolTable, ErrorReport &errorReport, DebugReport &debugReport)
Data Fields
bool trace_scanning = false
std::unique_ptr< AstTranslationUnit > translationUnit
Detailed Description
Definition at line 50 of file ParserDriver.h.
Constructor & Destructor Documentation
ParserDriver()
souffle::ParserDriver::ParserDriver () default
~ParserDriver()
souffle::ParserDriver::~ParserDriver () virtual default
Member Function Documentation
addClause()
void souffle::ParserDriver::addClause (std::unique_ptr< AstClause > c)
Definition at line 160 of file ParserDriver.cpp.
References translationUnit.
{
     translationUnit->getProgram()->addClause(std::move(c));
 }
addComponent()
void souffle::ParserDriver::addComponent (std::unique_ptr< AstComponent > c)
Definition at line 163 of file ParserDriver.cpp.
References translationUnit.
{
     translationUnit->getProgram()->addComponent(std::move(c));
 }
addFunctorDeclaration()
void souffle::ParserDriver::addFunctorDeclaration (std::unique_ptr< AstFunctorDeclaration > f)
Definition at line 103 of file ParserDriver.cpp.
References err, souffle::Diagnostic::ERROR, souffle::toString(), and translationUnit.
{
     const std::string& name = f->getName();
     if (AstFunctorDeclaration* prev = translationUnit->getProgram()->getFunctorDeclaration(name)) {
         Diagnostic err(Diagnostic::ERROR,
                 DiagnosticMessage("Redefinition of functor " + toString(name), f->getSrcLoc()),
                 {DiagnosticMessage("Previous definition", prev->getSrcLoc())});
         translationUnit->getErrorReport().addDiagnostic(err);
     } else {
         translationUnit->getProgram()->addFunctorDeclaration(std::move(f));
     }
 }
addInstantiation()
void souffle::ParserDriver::addInstantiation (std::unique_ptr< AstComponentInit > ci)
Definition at line 166 of file ParserDriver.cpp.
References translationUnit.
{
     translationUnit->getProgram()->addInstantiation(std::move(ci));
 }
addLoad()
void souffle::ParserDriver::addLoad (std::unique_ptr< AstLoad > d)
Definition at line 144 of file ParserDriver.cpp.
References translationUnit.
{
     translationUnit->getProgram()->addLoad(std::move(d));
 }
addPragma()
void souffle::ParserDriver::addPragma (std::unique_ptr< AstPragma > p)
Definition at line 99 of file ParserDriver.cpp.
References translationUnit.
{
     translationUnit->getProgram()->addPragma(std::move(p));
 }
addRelation()
void souffle::ParserDriver::addRelation (std::unique_ptr< AstRelation > r)
Definition at line 115 of file ParserDriver.cpp.
References err, souffle::Diagnostic::ERROR, souffle::toString(), and translationUnit.
{
     const auto& name = r->getName();
     if (AstRelation* prev = translationUnit->getProgram()->getRelation(name)) {
         Diagnostic err(Diagnostic::ERROR,
                 DiagnosticMessage("Redefinition of relation " + toString(name), r->getSrcLoc()),
                 {DiagnosticMessage("Previous definition", prev->getSrcLoc())});
         translationUnit->getErrorReport().addDiagnostic(err);
     } else {
         translationUnit->getProgram()->addRelation(std::move(r));
     }
 }
addStore()
void souffle::ParserDriver::addStore (std::unique_ptr< AstStore > d)
Definition at line 127 of file ParserDriver.cpp.
References err, souffle::Diagnostic::ERROR, souffle::toString(), and translationUnit.
{
     if (dynamic_cast<AstPrintSize*>(d.get()) != nullptr) {
         for (const auto& cur : translationUnit->getProgram()->getStores()) {
             if (cur->getName() == d->getName() && dynamic_cast<AstPrintSize*>(cur.get()) != nullptr) {
                 Diagnostic err(Diagnostic::ERROR,
                         DiagnosticMessage(
                                 "Redefinition of printsize directives for relation " + toString(d->getName()),
                                 d->getSrcLoc()),
                         {DiagnosticMessage("Previous definition", cur->getSrcLoc())});
                 translationUnit->getErrorReport().addDiagnostic(err);
                 return;
             }
         }
     }
     translationUnit->getProgram()->addStore(std::move(d));
 }
addType()
void souffle::ParserDriver::addType (std::unique_ptr< AstType > type)
Definition at line 148 of file ParserDriver.cpp.
References err, souffle::Diagnostic::ERROR, souffle::toString(), and translationUnit.
{
     const auto& name = type->getName();
     if (const AstType* prev = translationUnit->getProgram()->getType(name)) {
         Diagnostic err(Diagnostic::ERROR,
                 DiagnosticMessage("Redefinition of type " + toString(name), type->getSrcLoc()),
                 {DiagnosticMessage("Previous definition", prev->getSrcLoc())});
         translationUnit->getErrorReport().addDiagnostic(err);
     } else {
         translationUnit->getProgram()->addType(std::move(type));
     }
 }
error() [1/2]
void souffle::ParserDriver::error (const SrcLocation & loc, const std::string & msg)
Definition at line 177 of file ParserDriver.cpp.
References translationUnit.
{
     translationUnit->getErrorReport().addError(msg, loc);
 }
error() [2/2]
void souffle::ParserDriver::error (const std::string & msg)
Definition at line 180 of file ParserDriver.cpp.
References souffle::Diagnostic::ERROR, and translationUnit.
{
     translationUnit->getErrorReport().addDiagnostic(Diagnostic(Diagnostic::ERROR, DiagnosticMessage(msg)));
 }
getSymbolTable()
souffle::SymbolTable & souffle::ParserDriver::getSymbolTable ()
Definition at line 170 of file ParserDriver.cpp.
References translationUnit.
{
     return translationUnit->getSymbolTable();
 }
parse() [1/2]
std::unique_ptr< AstTranslationUnit > souffle::ParserDriver::parse (const std::string & filename, FILE * in, SymbolTable & symbolTable, ErrorReport & errorReport, DebugReport & debugReport)
Definition at line 47 of file ParserDriver.cpp.
References translationUnit, souffle::scanner_data::yyfilename, yylex_destroy(), yylex_init_extra(), and yyset_in().
Referenced by parseTranslationUnit().
{
     translationUnit = std::make_unique<AstTranslationUnit>(
             std::make_unique<AstProgram>(), symbolTable, errorReport, debugReport);
     yyscan_t scanner;
     scanner_data data;
     data.yyfilename = filename;
     yylex_init_extra(&data, &scanner);
     yyset_in(in, scanner);
     yy::parser parser(*this, scanner);
     parser.parse();
     yylex_destroy(scanner);
     translationUnit->getProgram()->finishParsing();
     return std::move(translationUnit);
 }
parse() [2/2]
std::unique_ptr< AstTranslationUnit > souffle::ParserDriver::parse (const std::string & code, SymbolTable & symbolTable, ErrorReport & errorReport, DebugReport & debugReport)
Definition at line 67 of file ParserDriver.cpp.
References translationUnit, yy_scan_string(), souffle::scanner_data::yyfilename, yylex_destroy(), and yylex_init_extra().
{
     translationUnit = std::make_unique<AstTranslationUnit>(
             std::make_unique<AstProgram>(), symbolTable, errorReport, debugReport);
     scanner_data data;
     data.yyfilename = "<in-memory>";
     yyscan_t scanner;
     yylex_init_extra(&data, &scanner);
     yy_scan_string(code.c_str(), scanner);
     yy::parser parser(*this, scanner);
     parser.parse();
     yylex_destroy(scanner);
     translationUnit->getProgram()->finishParsing();
     return std::move(translationUnit);
 }
parseTranslationUnit() [1/2]
std::unique_ptr< AstTranslationUnit > souffle::ParserDriver::parseTranslationUnit (const std::string & filename, FILE * in, SymbolTable & symbolTable, ErrorReport & errorReport, DebugReport & debugReport) static
Definition at line 87 of file ParserDriver.cpp.
References parse().
Referenced by souffle::main().
{
     ParserDriver parser;
     return parser.parse(filename, in, symbolTable, errorReport, debugReport);
 }
parseTranslationUnit() [2/2]
std::unique_ptr< AstTranslationUnit > souffle::ParserDriver::parseTranslationUnit (const std::string & code, SymbolTable & symbolTable, ErrorReport & errorReport, DebugReport & debugReport) static
Definition at line 93 of file ParserDriver.cpp.
References parse().
{
     ParserDriver parser;
     return parser.parse(code, symbolTable, errorReport, debugReport);
 }
warning()
void souffle::ParserDriver::warning (const SrcLocation & loc, const std::string & msg)
Definition at line 174 of file ParserDriver.cpp.
References translationUnit.
{
     translationUnit->getErrorReport().addWarning(msg, loc);
 }
Field Documentation
trace_scanning
bool souffle::ParserDriver::trace_scanning = false
Definition at line 69 of file ParserDriver.h.
translationUnit
std::unique_ptr<AstTranslationUnit> souffle::ParserDriver::translationUnit
Definition at line 55 of file ParserDriver.h.
Referenced by addClause(), addComponent(), addFunctorDeclaration(), addInstantiation(), addLoad(), addPragma(), addRelation(), addStore(), addType(), error(), getSymbolTable(), parse(), and warning().
The documentation for this class was generated from the following files:
ParserDriver.h
ParserDriver.cpp