souffle: souffle::AstAggregator Class Reference
souffle::AstAggregator Class Reference
An argument aggregating a value from a sub-query.
#include <AstArgument.h>
Public Types
enum Op { min, max, count, sum }
The kind of utilised aggregation operator.
Public Member Functions
void addBodyLiteral (std::unique_ptr< AstLiteral > lit)
Add body literal.
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
AstAggregator (Op fun)
Creates a new aggregation node.
void clearBodyLiterals ()
Clear body literals.
AstAggregator * clone () const override
Create clone.
std::vector< AstLiteral * > getBodyLiterals () const
Get body literals.
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
Op getOperator () const
Get aggregate operator.
const AstArgument * getTargetExpression () const
Get target expression.
void print (std::ostream &os) const override
Output to a given output stream.
void setTargetExpression (std::unique_ptr< AstArgument > arg)
Set target expression.
Public Member Functions inherited from souffle::AstNode
AstNode ()=default
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Private Attributes
std::vector< std::unique_ptr< AstLiteral > > body
A list of body-literals forming a sub-query which's result is projected and aggregated.
std::unique_ptr< AstArgument > expression
The expression to be aggregated.
Op fun
The aggregation operator of this aggregation step.
Detailed Description
An argument aggregating a value from a sub-query.
TODO (b-scholz): fix body literal interface; remove getters/setters for individual literals
Definition at line 498 of file AstArgument.h.
Member Enumeration Documentation
Op
enum souffle::AstAggregator::Op
The kind of utilised aggregation operator.
Note: lower-case is utilized due to a collision with constants in the parser.
Enumerator
min
max
count
sum
Definition at line 505 of file AstArgument.h.
 { min, max, count, sum };
Constructor & Destructor Documentation
AstAggregator()
souffle::AstAggregator::AstAggregator (Op fun) inline
Creates a new aggregation node.
Definition at line 508 of file AstArgument.h.
 : fun(fun), expression(nullptr) {}
Member Function Documentation
addBodyLiteral()
void souffle::AstAggregator::addBodyLiteral (std::unique_ptr< AstLiteral > lit) inline
Add body literal.
Definition at line 566 of file AstArgument.h.
{
         body.push_back(std::move(lit));
     }
apply()
void souffle::AstAggregator::apply (const AstNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::AstNode.
Definition at line 591 of file AstArgument.h.
{
         if (expression) {
             expression = map(std::move(expression));
         }
         for (auto& cur : body) {
             cur = map(std::move(cur));
         }
     }
clearBodyLiterals()
void souffle::AstAggregator::clearBodyLiterals () inline
Clear body literals.
Definition at line 561 of file AstArgument.h.
{
         body.clear();
     }
clone()
AstAggregator* souffle::AstAggregator::clone () const inline override virtual
Create clone.
Implements souffle::AstArgument.
Definition at line 581 of file AstArgument.h.
References souffle::AstNode::getSrcLoc().
{
         auto res = new AstAggregator(fun);
         res->expression = (expression) ? std::unique_ptr<AstArgument>(expression->clone()) : nullptr;
         for (const auto& cur : body) {
             res->body.emplace_back(cur->clone());
         }
         res->setSrcLoc(getSrcLoc());
         return res;
     }
equal()
bool souffle::AstAggregator::equal (const AstNode & other) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 601 of file AstArgument.h.
References souffle::equal_ptr(), souffle::equal_targets(), and fun.
{
         assert(nullptr != dynamic_cast<const AstAggregator*>(&node));
         const auto& other = static_cast<const AstAggregator&>(node);
         return fun == other.fun && equal_ptr(expression, other.expression) && equal_targets(body, other.body);
     }
getBodyLiterals()
std::vector<AstLiteral*> souffle::AstAggregator::getBodyLiterals () const inline
Get body literals.
Definition at line 556 of file AstArgument.h.
References souffle::toPtrVector().
Referenced by souffle::AstSemanticChecker::checkAggregator(), souffle::AstTranslator::ClauseTranslator::createValueIndex(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::MaterializeAggregationQueriesTransformer::needsMaterializedRelation(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::AstTranslator::ClauseTranslator::translateClause(), and souffle::usesInvalidWitness().
{
         return toPtrVector(body);
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstAggregator::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::AstNode.
Definition at line 570 of file AstArgument.h.
References souffle::AstNode::getChildNodes().
{
         auto res = AstArgument::getChildNodes();
         if (expression) {
             res.push_back(expression.get());
         }
         for (auto& cur : body) {
             res.push_back(cur.get());
         }
         return res;
     }
getOperator()
Op souffle::AstAggregator::getOperator () const inline
Get aggregate operator.
Definition at line 541 of file AstArgument.h.
Referenced by souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), and souffle::AstTranslator::ClauseTranslator::translateClause().
{
         return fun;
     }
getTargetExpression()
const AstArgument* souffle::AstAggregator::getTargetExpression () const inline
Get target expression.
Definition at line 551 of file AstArgument.h.
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstTranslator::ClauseTranslator::translateClause().
{
         return expression.get();
     }
print()
void souffle::AstAggregator::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 510 of file AstArgument.h.
References souffle::join().
{
         switch (fun) {
             case sum:
                 os << "sum";
                 break;
             case min:
                 os << "min";
                 break;
             case max:
                 os << "max";
                 break;
             case count:
                 os << "count";
                 break;
             default:
                 break;
         }
         if (expression) {
             os << " " << *expression;
         }
         os << " : ";
         if (body.size() > 1) {
             os << "{ ";
         }
         os << join(body, ", ", print_deref<std::unique_ptr<AstLiteral>>());
         if (body.size() > 1) {
             os << " }";
         }
     }
setTargetExpression()
void souffle::AstAggregator::setTargetExpression (std::unique_ptr< AstArgument > arg) inline
Set target expression.
Definition at line 546 of file AstArgument.h.
Referenced by souffle::getInlinedArgument().
{
         expression = std::move(arg);
     }
Field Documentation
body
std::vector<std::unique_ptr<AstLiteral> > souffle::AstAggregator::body private
A list of body-literals forming a sub-query which's result is projected and aggregated.
Definition at line 615 of file AstArgument.h.
expression
std::unique_ptr<AstArgument> souffle::AstAggregator::expression private
The expression to be aggregated.
Definition at line 612 of file AstArgument.h.
fun
Op souffle::AstAggregator::fun private
The aggregation operator of this aggregation step.
Definition at line 609 of file AstArgument.h.
Referenced by equal().
The documentation for this class was generated from the following file:
AstArgument.h