souffle: souffle::AstRelationIdentifier Class Reference
souffle::AstRelationIdentifier Class Reference
The type of identifier utilized for referencing relations.
#include <AstRelationIdentifier.h>
Public Member Functions
void append (const std::string &name)
AstRelationIdentifier (const std::string &name="")
AstRelationIdentifier (const char *name)
AstRelationIdentifier (std::vector< std::string > names)
AstRelationIdentifier (const AstRelationIdentifier &)=default
AstRelationIdentifier (AstRelationIdentifier &&)=default
std::string getName () const
const std::vector< std::string > & getNames () const
bool operator!= (const AstRelationIdentifier &other) const
bool operator< (const AstRelationIdentifier &other) const
AstRelationIdentifier & operator= (const AstRelationIdentifier &)=default
AstRelationIdentifier & operator= (AstRelationIdentifier &&)=default
bool operator== (const AstRelationIdentifier &other) const
void prepend (const std::string &name)
void print (std::ostream &out) const
Data Fields
std::vector< std::string > names
The list of names forming this identifier.
Friends
std::ostream & operator<< (std::ostream &out, const AstRelationIdentifier &id)
Detailed Description
The type of identifier utilized for referencing relations.
Relation name identifiers are hierarchically qualified names, e.g.
     problem.graph.edge
TODO (b-scholz): find better name (qualified name etc)
Definition at line 36 of file AstRelationIdentifier.h.
Constructor & Destructor Documentation
AstRelationIdentifier() [1/5]
souffle::AstRelationIdentifier::AstRelationIdentifier (const std::string & name = "") inline
Definition at line 40 of file AstRelationIdentifier.h.
Referenced by AstRelationIdentifier().
 : names(toVector(name)) {}
AstRelationIdentifier() [2/5]
souffle::AstRelationIdentifier::AstRelationIdentifier (const char * name) inline
Definition at line 42 of file AstRelationIdentifier.h.
 : AstRelationIdentifier(std::string(name)) {}
AstRelationIdentifier() [3/5]
souffle::AstRelationIdentifier::AstRelationIdentifier (std::vector< std::string > names) inline
Definition at line 44 of file AstRelationIdentifier.h.
References AstRelationIdentifier(), and operator=().
 : names(std::move(names)) {}
AstRelationIdentifier() [4/5]
souffle::AstRelationIdentifier::AstRelationIdentifier (const AstRelationIdentifier &) default
AstRelationIdentifier() [5/5]
souffle::AstRelationIdentifier::AstRelationIdentifier (AstRelationIdentifier &&) default
Member Function Documentation
append()
void souffle::AstRelationIdentifier::append (const std::string & name) inline
Definition at line 56 of file AstRelationIdentifier.h.
References names.
Referenced by souffle::AstSemanticChecker::checkProgram(), souffle::createAdornedIdentifier(), souffle::createMagicIdentifier(), souffle::createSubIdentifier(), and souffle::makeRelationName().
{
         names.push_back(name);
     }
getName()
std::string souffle::AstRelationIdentifier::getName () const inline
Definition at line 70 of file AstRelationIdentifier.h.
References souffle::join(), names, and souffle::profile::ss.
Referenced by souffle::addBackwardDependencies(), souffle::AstTranslator::getEvaluationArity(), souffle::AstProfileUse::getRelationSize(), souffle::AstProfileUse::hasRelationSize(), souffle::reduceSingletonRelations(), souffle::Adornment::run(), souffle::ReduceExistentialsTransformer::transform(), and souffle::MagicSetTransformer::transform().
{
         std::stringstream ss;
         ss << join(names, ".");
         return ss.str();
     }
getNames()
const std::vector<std::string>& souffle::AstRelationIdentifier::getNames () const inline
Definition at line 66 of file AstRelationIdentifier.h.
References names.
Referenced by souffle::createAdornedIdentifier(), souffle::createMagicIdentifier(), souffle::createSubIdentifier(), souffle::extractAdornment(), souffle::isAggRel(), and souffle::MagicSetTransformer::transform().
{
         return names;
     }
operator!=()
bool souffle::AstRelationIdentifier::operator!= (const AstRelationIdentifier & other) const inline
Definition at line 82 of file AstRelationIdentifier.h.
{
         return !(*this == other);
     }
operator<()
bool souffle::AstRelationIdentifier::operator< (const AstRelationIdentifier & other) const inline
Definition at line 86 of file AstRelationIdentifier.h.
References names.
{
         return std::lexicographical_compare(
                 names.begin(), names.end(), other.names.begin(), other.names.end());
     }
operator=() [1/2]
AstRelationIdentifier& souffle::AstRelationIdentifier::operator= (const AstRelationIdentifier &) default
Referenced by AstRelationIdentifier().
operator=() [2/2]
AstRelationIdentifier& souffle::AstRelationIdentifier::operator= (AstRelationIdentifier &&) default
operator==()
bool souffle::AstRelationIdentifier::operator== (const AstRelationIdentifier & other) const inline
Definition at line 78 of file AstRelationIdentifier.h.
References names.
{
         return names == other.names;
     }
prepend()
void souffle::AstRelationIdentifier::prepend (const std::string & name) inline
Definition at line 60 of file AstRelationIdentifier.h.
References names.
Referenced by souffle::operator+().
{
         names.insert(names.begin(), name);
     }
print()
void souffle::AstRelationIdentifier::print (std::ostream & out) const inline
Definition at line 91 of file AstRelationIdentifier.h.
References souffle::join(), and names.
{
         out << join(names, ".");
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const AstRelationIdentifier & id) friend
Definition at line 95 of file AstRelationIdentifier.h.
{
         id.print(out);
         return out;
     }
Field Documentation
names
std::vector<std::string> souffle::AstRelationIdentifier::names
The list of names forming this identifier.
Definition at line 102 of file AstRelationIdentifier.h.
Referenced by append(), getName(), getNames(), operator<(), operator==(), prepend(), and print().
The documentation for this class was generated from the following file:
AstRelationIdentifier.h