souffle: souffle::TypeEnvironmentAnalysis Class Reference
souffle::TypeEnvironmentAnalysis Class Reference
#include <AstTypeEnvironmentAnalysis.h>
Public Member Functions
const TypeEnvironment & getTypeEnvironment ()
void print (std::ostream &os) const override
print the analysis result in HTML format
void run (const AstTranslationUnit &translationUnit) override
run analysis for a RAM translation unit
Public Member Functions inherited from souffle::AstAnalysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "type-environment"
Private Member Functions
void updateTypeEnvironment (const AstProgram &program)
A utility function utilized by the finishParsing member function to update a type environment out of a given list of types in the AST.
Private Attributes
TypeEnvironment env
Detailed Description
Definition at line 28 of file AstTypeEnvironmentAnalysis.h.
Member Function Documentation
getTypeEnvironment()
const TypeEnvironment& souffle::TypeEnvironmentAnalysis::getTypeEnvironment () inline
Definition at line 36 of file AstTypeEnvironmentAnalysis.h.
References env.
{
         return env;
     }
print()
void souffle::TypeEnvironmentAnalysis::print (std::ostream & os) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::AstAnalysis.
Definition at line 31 of file AstTypeEnvironmentAnalysis.cpp.
References env, and souffle::TypeEnvironment::print().
{
     env.print(os);
 }
run()
void souffle::TypeEnvironmentAnalysis::run (const AstTranslationUnit & translationUnit) override virtual
run analysis for a RAM translation unit
Implements souffle::AstAnalysis.
Definition at line 27 of file AstTypeEnvironmentAnalysis.cpp.
References souffle::AstTranslationUnit::getProgram(), and updateTypeEnvironment().
{
     updateTypeEnvironment(*translationUnit.getProgram());
 }
updateTypeEnvironment()
void souffle::TypeEnvironmentAnalysis::updateTypeEnvironment (const AstProgram & program) private
A utility function utilized by the finishParsing member function to update a type environment out of a given list of types in the AST.
Parameters
types the types specified in the input file, contained in the AST
env the type environment to be updated
Definition at line 42 of file AstTypeEnvironmentAnalysis.cpp.
References souffle::UnionType::add(), souffle::RecordType::add(), souffle::TypeEnvironment::createNumericType(), souffle::TypeEnvironment::createRecordType(), souffle::TypeEnvironment::createSymbolType(), souffle::TypeEnvironment::createUnionType(), env, souffle::TypeEnvironment::getModifiableType(), souffle::TypeEnvironment::getType(), souffle::AstProgram::getTypes(), souffle::TypeEnvironment::isType(), and name.
Referenced by run().
{
     // build up new type system based on defined types
     // create all type symbols in a first step
     for (const auto& cur : program.getTypes()) {
         // support faulty codes with multiple definitions
         if (env.isType(cur->getName())) {
             continue;
         }
         // create type within type environment
         if (auto* t = dynamic_cast<const AstPrimitiveType*>(cur)) {
             if (t->isNumeric()) {
                 env.createNumericType(cur->getName());
             } else {
                 env.createSymbolType(cur->getName());
             }
         } else if (dynamic_cast<const AstUnionType*>(cur) != nullptr) {
             // initialize the union
             env.createUnionType(cur->getName());
         } else if (dynamic_cast<const AstRecordType*>(cur) != nullptr) {
             // initialize the record
             env.createRecordType(cur->getName());
         } else {
             std::cout << "Unsupported type construct: " << typeid(cur).name() << "\n";
             assert(false && "Unsupported Type Construct!");
         }
     }
     // link symbols in a second step
     for (const auto& cur : program.getTypes()) {
         Type* type = env.getModifiableType(cur->getName());
         assert(type && "It should be there!");
         if (dynamic_cast<const AstPrimitiveType*>(cur) != nullptr) {
             // nothing to do here
         } else if (auto* t = dynamic_cast<const AstUnionType*>(cur)) {
             // get type as union type
             auto* ut = dynamic_cast<UnionType*>(type);
             if (ut == nullptr) {
                 continue;  // support faulty input
             }
             // add element types
             for (const auto& cur : t->getTypes()) {
                 if (env.isType(cur)) {
                     ut->add(env.getType(cur));
                 }
             }
         } else if (auto* t = dynamic_cast<const AstRecordType*>(cur)) {
             // get type as record type
             auto* rt = dynamic_cast<RecordType*>(type);
             if (rt == nullptr) {
                 continue;  // support faulty input
             }
             // add fields
             for (const auto& f : t->getFields()) {
                 if (env.isType(f.type)) {
                     rt->add(f.name, env.getType(f.type));
                 }
             }
         } else {
             std::cout << "Unsupported type construct: " << typeid(cur).name() << "\n";
             assert(false && "Unsupported Type Construct!");
         }
     }
 }
Field Documentation
env
TypeEnvironment souffle::TypeEnvironmentAnalysis::env private
Definition at line 41 of file AstTypeEnvironmentAnalysis.h.
Referenced by getTypeEnvironment(), print(), and updateTypeEnvironment().
name
constexpr const char* souffle::TypeEnvironmentAnalysis::name = "type-environment" static
Definition at line 30 of file AstTypeEnvironmentAnalysis.h.
Referenced by updateTypeEnvironment().
The documentation for this class was generated from the following files:
AstTypeEnvironmentAnalysis.h
AstTypeEnvironmentAnalysis.cpp