souffle: souffle::RecordTable Class Reference
souffle::RecordTable Class Reference
#include <RecordTable.h>
Public Member Functions
RamDomain getNil () const
bool isNil (RamDomain ref) const
Determines whether the given reference is the nil reference encoding the absence of any nested record.
RamDomain pack (RamDomain *tuple, size_t arity)
A function packing a tuple of the given arity into a reference.
RamDomain pack (const std::vector< RamDomain > &vector)
A function packing a vector into a reference.
template<typename Domain , std::size_t Arity>
RamDomain pack (ram::Tuple< Domain, Arity > tuple)
A function packing a tuple of the given arity into a reference.
RecordTable ()=default
RamDomain * unpack (RamDomain ref, size_t arity)
A function obtaining a pointer to the tuple addressed by the given reference.
const RamDomain * unpack (RamDomain ref, size_t arity) const
A function obtaining a pointer to the tuple addressed by the given reference.
template<typename Domain , std::size_t Arity>
ram::Tuple< Domain, Arity > unpackTuple (RamDomain ref)
A function obtaining a pointer to the tuple addressed by the given reference.
virtual ~RecordTable ()=default
Private Member Functions
RecordMap & getForArity (size_t arity)
Private Attributes
std::unordered_map< size_t, RecordMap > maps
Detailed Description
Definition at line 106 of file RecordTable.h.
Constructor & Destructor Documentation
RecordTable()
souffle::RecordTable::RecordTable () default
~RecordTable()
virtual souffle::RecordTable::~RecordTable () virtual default
Member Function Documentation
getForArity()
RecordMap& souffle::RecordTable::getForArity (size_t arity) inline private
Definition at line 182 of file RecordTable.h.
{
         std::unordered_map<size_t, RecordMap>::iterator mapsIterator;
 #pragma omp critical(RecordTableGetForArity)
         {
             // This will create a new map if it doesn't exist yet.
             mapsIterator = maps.emplace(arity, arity).first;
         }
         return mapsIterator->second;
     }
getNil()
RamDomain souffle::RecordTable::getNil () const inline
Definition at line 175 of file RecordTable.h.
Referenced by souffle::ReadStream::readRecord().
{
         return 0;
     }
isNil()
bool souffle::RecordTable::isNil (RamDomain ref) const inline
Determines whether the given reference is the nil reference encoding the absence of any nested record.
Definition at line 171 of file RecordTable.h.
Referenced by souffle::InterpreterEngine::execute(), and souffle::WriteStream::outputRecord().
{
         return ref == getNil();
     }
pack() [1/3]
RamDomain souffle::RecordTable::pack (RamDomain * tuple, size_t arity) inline
A function packing a tuple of the given arity into a reference.
Definition at line 114 of file RecordTable.h.
Referenced by souffle::InterpreterEngine::execute(), and souffle::ReadStream::readRecord().
{
         return getForArity(arity).pack(tuple);
     }
pack() [2/3]
RamDomain souffle::RecordTable::pack (const std::vector< RamDomain > & vector) inline
A function packing a vector into a reference.
Definition at line 121 of file RecordTable.h.
References souffle::RecordMap::pack().
{
         return getForArity(vector.size()).pack(vector);
     }
pack() [3/3]
template<typename Domain , std::size_t Arity> RamDomain souffle::RecordTable::pack (ram::Tuple< Domain, Arity > tuple) inline
A function packing a tuple of the given arity into a reference.
Definition at line 129 of file RecordTable.h.
References souffle::ram::Tuple< Domain, _arity >::data.
{
         return getForArity(Arity).pack(static_cast<RamDomain*>(tuple.data));
     }
unpack() [1/2]
RamDomain* souffle::RecordTable::unpack (RamDomain ref, size_t arity) inline
A function obtaining a pointer to the tuple addressed by the given reference.
Definition at line 136 of file RecordTable.h.
Referenced by souffle::InterpreterEngine::execute(), and souffle::WriteStream::outputRecord().
{
         auto iter = maps.find(arity);
         assert(iter != maps.end() && "Attempting to unpack non-existing record");
         return (iter->second).unpack(ref);
     }
unpack() [2/2]
const RamDomain* souffle::RecordTable::unpack (RamDomain ref, size_t arity) const inline
A function obtaining a pointer to the tuple addressed by the given reference.
Definition at line 146 of file RecordTable.h.
{
         auto iter = maps.find(arity);
         assert(iter != maps.end() && "Attempting to unpack non-existing record");
         return (iter->second).unpack(ref);
     }
unpackTuple()
template<typename Domain , std::size_t Arity> ram::Tuple<Domain, Arity> souffle::RecordTable::unpackTuple (RamDomain ref) inline
A function obtaining a pointer to the tuple addressed by the given reference.
Definition at line 157 of file RecordTable.h.
References souffle::ram::Tuple< Domain, _arity >::data, and i.
{
         ram::Tuple<RamDomain, Arity> tuple;
         RamDomain* data = getForArity(Arity).unpack(ref);
         for (size_t i = 0; i < Arity; ++i) {
             tuple.data[i] = data[i];
         }
         return tuple;
     }
Field Documentation
maps
std::unordered_map<size_t, RecordMap> souffle::RecordTable::maps private
Definition at line 180 of file RecordTable.h.
The documentation for this class was generated from the following file:
RecordTable.h