souffle: souffle::AstLoad Class Reference
souffle::AstLoad Class Reference
Intermediate representation of a store operation.
#include <AstIO.h>
Public Member Functions
AstLoad (const AstIO &io)
AstLoad ()=default
AstLoad * clone () const override
Create a clone (i.e.
void print (std::ostream &os) const override
Output to a given output stream.
Public Member Functions inherited from souffle::AstIO
void addKVP (const std::string &key, const std::string &value)
add key-value pair
AstIO (const AstIO &io)
AstIO ()=default
const std::map< std::string, std::string > & getIODirectiveMap () const
get I/O-directive map
const AstRelationIdentifier & getName () const
relation name of I/O-directive
void setName (const AstRelationIdentifier &name)
set relation name of I/O-directive
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &mapper)
Apply the mapper to all child nodes.
AstNode ()=default
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Additional Inherited Members
Protected Member Functions inherited from souffle::AstIO
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Protected Attributes inherited from souffle::AstIO
std::map< std::string, std::string > kvps
key-value pair map
AstRelationIdentifier name
relation name of I/O directive
Detailed Description
Intermediate representation of a store operation.
Definition at line 116 of file AstIO.h.
Constructor & Destructor Documentation
AstLoad() [1/2]
souffle::AstLoad::AstLoad (const AstIO & io) inline
Definition at line 118 of file AstIO.h.
References souffle::AstNode::getSrcLoc(), and souffle::AstNode::setSrcLoc().
                              : AstIO(io) {
         setSrcLoc(io.getSrcLoc());
     }
AstLoad() [2/2]
souffle::AstLoad::AstLoad () default
Member Function Documentation
clone()
AstLoad* souffle::AstLoad::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Reimplemented from souffle::AstIO.
Definition at line 128 of file AstIO.h.
References souffle::AstNode::getSrcLoc(), souffle::AstIO::kvps, and souffle::AstIO::name.
{
         auto res = new AstLoad();
         res->name = name;
         res->kvps = kvps;
         res->setSrcLoc(getSrcLoc());
         return res;
     }
print()
void souffle::AstLoad::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Reimplemented from souffle::AstIO.
Definition at line 123 of file AstIO.h.
References souffle::AstIO::print().
{
         os << ".input ";
         AstIO::print(os);
     }
The documentation for this class was generated from the following file:
AstIO.h