souffle: souffle::IndirectIndex::IndirectIndexView Struct Reference
souffle::IndirectIndex::IndirectIndexView Struct Reference
Public Member Functions
bool contains (const TupleRef &tuple) const override
Tests whether the given entry is contained in this index.
bool contains (const TupleRef &low, const TupleRef &high) const override
Tests whether any element in the given range is contained in this index.
size_t getArity () const override
Return arity size of the index.
IndirectIndexView (const IndirectIndex &index)
Stream range (const TupleRef &low, const TupleRef &high) const override
Obtains a stream for the given range within this index.
Public Member Functions inherited from souffle::IndexView
virtual ~IndexView ()=default
Data Fields
Hints hints
const IndirectIndex & index
Detailed Description
Definition at line 474 of file InterpreterIndex.cpp.
Constructor & Destructor Documentation
IndirectIndexView()
souffle::IndirectIndex::IndirectIndexView::IndirectIndexView (const IndirectIndex & index) inline
Definition at line 478 of file InterpreterIndex.cpp.
 : index(index) {}
Member Function Documentation
contains() [1/2]
bool souffle::IndirectIndex::IndirectIndexView::contains (const TupleRef & entry) const inline override virtual
Tests whether the given entry is contained in this index.
Implements souffle::IndexView.
Definition at line 480 of file InterpreterIndex.cpp.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::contains(), and souffle::IndirectIndex::set.
Referenced by souffle::IndirectIndex::contains().
{
             return index.set.contains(tuple, hints);
         }
contains() [2/2]
bool souffle::IndirectIndex::IndirectIndexView::contains (const TupleRef & low, const TupleRef & high) const inline override virtual
Tests whether any element in the given range is contained in this index.
Implements souffle::IndexView.
Definition at line 484 of file InterpreterIndex.cpp.
{
             assert(false && "Not implemented!");
             return false;
         }
getArity()
size_t souffle::IndirectIndex::IndirectIndexView::getArity () const inline override virtual
Return arity size of the index.
Implements souffle::IndexView.
Definition at line 494 of file InterpreterIndex.cpp.
References souffle::IndirectIndex::getArity().
{
             return index.getArity();
         }
range()
Stream souffle::IndirectIndex::IndirectIndexView::range (const TupleRef & low, const TupleRef & high) const inline override virtual
Obtains a stream for the given range within this index.
Implements souffle::IndexView.
Definition at line 489 of file InterpreterIndex.cpp.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::lower_bound(), souffle::IndirectIndex::set, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::upper_bound().
Referenced by souffle::IndirectIndex::range().
{
             return std::make_unique<Source>(
                     index.set.lower_bound(low, hints), index.set.upper_bound(high, hints));
         }
Field Documentation
hints
Hints souffle::IndirectIndex::IndirectIndexView::hints mutable
Definition at line 476 of file InterpreterIndex.cpp.
index
const IndirectIndex& souffle::IndirectIndex::IndirectIndexView::index
Definition at line 475 of file InterpreterIndex.cpp.
The documentation for this struct was generated from the following file:
InterpreterIndex.cpp